### ISSUE TITLE
ShippingEasy.Client.CancelOrder() error

### ISSUE THREAD

**Issue by TheFigmo** [ShippingEasy/shipping_easy-dotnet#4]
Have code that has been working for months with no recent changes that suddenly began throwing the following exception this week:

System.Net.Web.Exception "The server committed a protocol violation.  Section=ResponseHeader Detail=CR must be followed by LF"

` var client = new ShippingEasy.Client(Properties.Settings.Default.ShippingEasyApiKey, Properties.Settings.Default.ShippingEasyApiPassword);                   
  var response = client.CancelOrder(Properties.Settings.Default.ShippingEasyStoreApiKey, ((nopOrder) nopOrderBindingSource.DataSource).Id.ToString());
`

**Comment by robmack** [comment]
This should be fixed now. It was related to a server configuration change we made.
